// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Point = {};

var Delta = {};

var Distance = {};

var Dimensions = {};

var Rect = {};

var Margins = {};

var Borders = {};

var Paddings = {};

var Offset = {};

var Scroll = {};

var CanScroll = {};

var Axis = {};

var Arrow = {};

var Direction = {};

var AxisDirection = {};

var RelativityBag = {};

var Geometry = {};

var Shift = {};

var ScrollableElement = {};

var ItemBag = {};

var ContainerBag = {};

var Ghost = {};

var Pawn = {};

var Subscriptions = {};

var ReorderResult = {};

var Status = {};

exports.Point = Point;
exports.Delta = Delta;
exports.Distance = Distance;
exports.Dimensions = Dimensions;
exports.Rect = Rect;
exports.Margins = Margins;
exports.Borders = Borders;
exports.Paddings = Paddings;
exports.Offset = Offset;
exports.Scroll = Scroll;
exports.CanScroll = CanScroll;
exports.Axis = Axis;
exports.Arrow = Arrow;
exports.Direction = Direction;
exports.AxisDirection = AxisDirection;
exports.RelativityBag = RelativityBag;
exports.Geometry = Geometry;
exports.Shift = Shift;
exports.ScrollableElement = ScrollableElement;
exports.ItemBag = ItemBag;
exports.ContainerBag = ContainerBag;
exports.Ghost = Ghost;
exports.Pawn = Pawn;
exports.Subscriptions = Subscriptions;
exports.ReorderResult = ReorderResult;
exports.Status = Status;
/* No side effect */
